@TARGET_GUILD_ID=750480529765171302
@TARGET_GUILD_COMMAND_NAME=dice
@TARGET_GUILD_COMMAND_ID=820920769911193610


### Get Global Commands
GET https://discord.com/api/v8/applications/{{Client-ID}}/commands HTTP/1.1
Authorization: Bot {{Client-Token}}
### Get Global Command
GET https://discord.com/api/v8/applications/{{Client-ID}}/commands/{{TARGET_GUILD_ID}} HTTP/1.1
Authorization: Bot {{Client-Token}}


### Get Guild Commands
GET https://discord.com/api/v8/applications/{{Client-ID}}/guilds/{{TARGET_GUILD_ID}}/commands HTTP/1.1
Authorization: Bot {{Client-Token}}
### Get Guild Command
GET https://discord.com/api/v8/applications/{{Client-ID}}/guilds/{{TARGET_GUILD_ID}}/commands/{{TARGET_GUILD_COMMAND_ID}} HTTP/1.1
Authorization: Bot {{Client-Token}}


### Create Guild Command
POST https://discord.com/api/v8/applications/{{Client-ID}}/guilds/{{TARGET_GUILD_ID}}/commands
Authorization: Bot {{Client-Token}}
Content-Type: application/json

<@ ./src/slash_command_modules/{{TARGET_GUILD_COMMAND_NAME}}_data.json


### Edit Guild Command
PATCH https://discord.com/api/v8/applications/{{Client-ID}}/guilds/{{TARGET_GUILD_ID}}/commands/{{TARGET_GUILD_COMMAND_ID}}
Authorization: Bot {{Client-Token}}
Content-Type: application/json

<@ ./src/slash_command_modules/{{TARGET_GUILD_COMMAND_NAME}}_data.json


### Delete Guild Command
DELETE https://discord.com/api/v8/applications/{{Client-ID}}/guilds/{{TARGET_GUILD_ID}}/commands/{{TARGET_GUILD_COMMAND_ID}} HTTP/1.1
Authorization: Bot {{Client-Token}}





### Check Creed Services
GET https://us-central1-creed-services.cloudfunctions.net/put-command HTTP/1.1
Authorization: bearer {{GCloud-Identity-Token}}
